{% set version = "23.4.11" %}

package:
  name: vnu-validator
  version: {{ version }}

source:
  # building from source is... untenable due to sh/py/ant/java/git sandwich
  - url: https://registry.npmjs.org/vnu-jar/-/vnu-jar-{{ version }}.tgz
    sha256: cbba595a86d680d48e9c5261a16d9ef409e5658ad8aa47081c593690a652cf0f
  # this is _not_ distributed on npm
  - fn: CREDITS-{{ version }}
    url: https://raw.githubusercontent.com/validator/validator/{{ version }}/CREDITS
    sha256: b7f78e603da0e9aa19adb63a3c12af5c8c16e40c43ac115a017cc7ed2517e9fb

build:
  number: 0
  noarch: generic

requirements:
  run:
    - __unix  # [unix]
    - __win   # [win]
    - openjdk >=8

test:
  requires:
    - m2-grep  # [win]
    - python *
    - pytest

about:
  home: https://validator.github.io/validator
  license: MIT
  license_file:
    - LICENSE
    - CREDITS-{{ version }}
  summary: Helps you catch problems in your HTML/CSS/SVG
  dev_url: https://github.com/validator/validator

extra:
  recipe-maintainers:
    - bollwyvl
